apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=    # "postgres" (Base64-кодировка)
  postgres-password: cGFzc3dvcmQ=    # "password" (Base64-кодировка)
  mongodb-username: bW9uZ29kbw==    # "mongodb" (Base64)
  mongodb-password: cGFzc3dvcmQ=    # "password" (Base64)