
services:


  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    env_file:
      - .env
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data_1
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring_resources_app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATASOURCE_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - spring_resources_app-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - spring_resources_app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - spring_resources_app-network

  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - spring_resources_app-network


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
    networks:
      - spring_resources_app-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      DB_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    command: >
      start-dev --http-relative-path /auth
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring_resources_app-network


  gateway-service:
    image: apigateway:latest
    container_name: gateway-service
    build:
        context: ./gateway-service
        dockerfile: Dockerfile
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - redis
      - eureka-server
    networks:
      - spring_resources_app-network

  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    image: driver-service
    container_name: driver-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/driver_db"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
      - kafka
    networks:
      - spring_resources_app-network

  passenger-service:
    build:
      context: ./passenger-service
      dockerfile: Dockerfile
    image: passenger-service
    container_name: passenger-service
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/passenger_db"
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eureka-server
      - postgres
      - kafka
    networks:
      - spring_resources_app-network

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    image: payment-service
    container_name: payment-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - spring_resources_app-network


  ride-service:
    build:
      context: ./ride-service
      dockerfile: Dockerfile
    image: ride-service
    container_name: ride-service
    environment:
        SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/ride_db"
        SPRING_DATA_MONGODB_DATABASE: ride_db
        SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://host.docker.internal:8761/eureka/
    depends_on:
      - eureka-server
      - mongodb
      - kafka
    networks:
      - spring_resources_app-network


volumes:
  postgres_data:
  mongodb_data:
  redis-data:

networks:
  spring_resources_app-network:
    driver: bridge

