spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/**
          filters:
             - Retry=3
             - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
        - id: driver-service
          uri: http://driver-service:8081
          predicates:
            - Path=/**
          filters:
            - Retry=3
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
        - id: passenger-service
          uri: http://passenger-service:8083
          predicates:
            - Path=/**
          filters:
            - Retry=3
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
        - id: ride-service
          uri: http://ride-service:8084
          predicates:
            - Path=/**
          filters:
            - Retry=3
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}




eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

  session:
    store-type: redis
  redis:
    host: redis
    port: 6379



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG

server:
  port: 8086
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false



