spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
    
  cloud:
    gateway:
      httpclient:
        response-timeout: 1500ms
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment-service/**
          filters:
            - Retry=3
            - RewritePath=/payment-service/(?<path>.*), /${path}
            - name: CircuitBreaker
              args:
                name: paymentServiceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=/passenger-service/**
          filters:
            - Retry=3
            - RewritePath=/passenger-service/(?<path>.*), /${path}
            - name: CircuitBreaker
              args:
                name: passengerServiceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=/driver-service/**
          filters:
            - Retry=3
            - RewritePath=/driver-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: driverServiceCircuitBreaker
                fallbackUri: forward:/fallback
        - id: ride-service
          uri: lb://ride-service
          predicates:
            - Path=/ride-service/**
          filters:
            - Retry=3
            - RewritePath=/ride-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: rideServiceCircuitBreaker
                fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true



management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


  session:
    store-type: redis
  redis:
    host: redis
    port: 6379



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG

server:
  forward-headers-strategy: framework
  port: 8086


resilience4j:
  circuitbreaker:
    instances:
      paymentServiceCircuitBreaker:
        failureRateThreshold: 70
        slowCallRateThreshold: 100
        slowCallDurationThreshold: 2s
        permittedNumberOfCallsInHalfOpenState: 3
        maxWaitDurationInHalfOpenState: 5s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 2
        waitDurationInOpenState: 10s



