spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  session:
    store-type: redis
  redis:
    host: redis
    port: 6379

  spring:
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        routes:
          - id: driver-service
            uri: lb://DRIVER-SERVICE
            predicates:
              - Path=/drivers/**
            filters:
              - TokenRelay
              - Retry=3
          - id: passenger-service
            uri: lb://PASSENGER-SERVICE
            predicates:
              - Path=/passengers/**
            filters:
              - TokenRelay
               - Retry=3
          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
               - Path=/payments/**
            filters:
               - Retry=3
          - id: ride-service
            uri: lb://RIDE-SERVICE
            predicates:
              - Path=/rides/**
            filters:
               - Retry=3

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true



  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG
server:
  port: 8086