spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://payment-service:8082
          predicates:
            - Path=/payment-service/**
          filters:
             - Retry=3
             - RewritePath=/payment-service/v3/api-docs, /v3/api-docs
             - RewritePath=/payment-service/swagger-ui/(.*), /swagger-ui/$1
        - id: passenger-service
          uri: http://passenger-service:8083
          predicates:
            - Path=/passenger-service/**
          filters:
            - Retry=3
            - RewritePath=/passenger-service/v3/api-docs, /v3/api-docs
            - RewritePath=/passenger-service/swagger-ui/(.*), /swagger-ui/$1

        - id: driver-service
          uri: http://driver-service:8081
          predicates:
            - Path=/driver-service/**
          filters:
            - Retry=3

            - RewritePath=/driver-service/v3/api-docs, /v3/api-docs
            - RewritePath=/driver-service/swagger-ui/(.*), /swagger-ui/$1

        - id: ride-service
          uri: http://ride-service:8084
          predicates:
            - Path=/ride-service/**
          filters:
            - Retry=3
            - RewritePath=/ride-service/v3/api-docs, /v3/api-docs
            - RewritePath=/ride-service/swagger-ui/(.*), /swagger-ui/$1
            - RewritePath=/ride-service/v3/api-docs/swagger-config, /v3/api-docs/swagger-config
            - RewritePath=/ride-service/swagger-ui/oauth2-redirect.html, /swagger-ui/oauth2-redirect.html





eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

  session:
    store-type: redis
  redis:
    host: redis
    port: 6379



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.circuitbreaker: DEBUG

server:
  port: 8086
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    urls:
      - name: Passenger Service
        url: /passenger-service/v3/api-docs
      - name: Payment Service
        url: /payment-service/v3/api-docs
      - name: Driver Service
        url: /driver-service/v3/api-docs
      - name: Ride Service
        url: /ride-service/v3/api-docs
    enabled: false
  api-docs:
    enabled: false



