server:
  port: 8086

spring:
  application:
    name: gateway-service


  session:
    store-type: redis
  redis:
    host: redis
    port: 6379


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - TokenRelay
            - Retry=5
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - TokenRelay
            - Retry=3
      discovery:
        locator:
          enabled: true
      default-filters:
        - name: CircuitBreaker
          args:
            name: myCircuitBreaker
            fallbackUri: forward:/fallback

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5


  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: gateway-client
            client-secret: <???_??????_???????>
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8085/login/oauth2/code/keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/my-realm

