spring:
  application:
         name: payment-service
eureka:
  instance:
    hostname: payment-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

springdoc:
  swagger-ui:
    path: /swagger-ui
    url: /payment-service/v3/api-docs
    configUrl: /payment-service/v3/api-docs/swagger-config

server:
  port: 8082
