spring:
  config:
    activate:
      on-profile: dev
  datasource:
   url: jdbc:postgresql://postgres:5432/driver_db?createDatabaseIfNotExist=true
   username: ${SPRING_DATASOURCE_USERNAME}
   password: ${SPRING_DATASOURCE_PASSWORD}
   driver-class-name: org.postgresql.Driver
  liquibase:

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            provider: keycloak
#            client-id: spring-app
#            client-secret: GFr6740iTqzHfFcB0YeQBEHyoRSKIXnJ
#            authorization-grant-type: password
#            scope: openid
#      provider:
#        keycloak:
#          issuer-uri: http://localhost:8080/auth/realms/spring_resources


  jpa:
    show:
      sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8081
  servlet:
    context-path: /driver-service
  forward-headers-strategy: framework