spring:
  application:
    name: driver-service

eureka:
  instance:
    hostname: DRIVER-SERVICE
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

server:
  port: 8081
  servlet:
    context-path: /driver-service
  forward-headers-strategy: framework