spring:
  config:
    activate:
      on-profile: dev
  datasource:
   url: jdbc:postgresql://postgres:5432/driver_db?createDatabaseIfNotExist=true
   username: ${SPRING_DATASOURCE_USERNAME}
   password: ${SPRING_DATASOURCE_PASSWORD}
   driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: false

  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1.0

  jpa:
    show:
      sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8081
  servlet:
    context-path: /driver-service
  forward-headers-strategy: framework