spring:
  application:
    name: driver-service
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-host:8761/eureka/
  instance:
    preferIpAddress: true