spring:
  application:
    name: driver-service

eureka:
  instance:
    hostname: DRIVER-SERVICE
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    enabled: true


server:
  port: 8081
  forward-headers-strategy: framework