eureka:
  instance:
    hostname: eureka-server
  server:
    peer-node-read-timeout-ms: 10000
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8761
