spring:
  application:
   name: ride-service

eureka:
  instance:
    hostname: RIDE-SERVICE
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

springdoc:
  swagger-ui:
    path: /swagger-ui
    url: /ride-service/v3/api-docs
    configUrl: /ride-service/v3/api-docs/swagger-config
  api-docs:
    enabled: true


server:
  port: 8084
  forward-headers-strategy: framework