spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: mongodb://localhost:27017/ride_db
      database: ride_db

  kafka:
   bootstrap-servers: kafka:9092
   consumer:
     key-deserializer: ${KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
     value-deserializer: ${KAFKA_CONSUMER_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
     group-id: ride-group
     auto-offset-reset: earliest

   liquibase:
     change-log: classpath:db/changelog/db.changelog-master.json
     data:
       mongodb:
         uri: mongodb://localhost:27017/ride_db