spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: ${KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      value-deserializer: ${KAFKA_CONSUMER_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
      group-id: ride-group
      auto-offset-reset: earliest