spring:
 application:
   name: passenger-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
logging:
  level:
    root: ERROR
    org:
     springframework: DEBUG
     hibernate: DEBUG
server:
  port: 0
  forward-headers-strategy: framework