spring:
 application:
   name: passenger-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

springdoc:
  swagger-ui:
    path: /swagger-ui
logging:
  level:
    root: ERROR
    org:
     springframework: DEBUG
     hibernate: DEBUG
server:
  port: 8083