spring:
  application:
         name: payment-service
eureka:
  instance:
    hostname: PAYMENT-SERVICE
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/


  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8082
  forward-headers-strategy: framework
  servlet:
    context-path: /payment-service
