spring:
  application:
         name: payment-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

  redis:
    host: redis
    port: 6379
  session:
    store-type: redis

springdoc:
  swagger-ui:
    path: /swagger-ui

server:
  port: 8082
