spring:
  application:
         name: payment-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-host:8761/eureka/
  instance:
    preferIpAddress: true

  redis:
    host: redis
    port: 6379
  session:
    store-type: redis